### ISSUE TITLE
Resubscribing a member returns 500

### ISSUE THREAD

**Issue by sam0901** [thorning/node-mailchimp#35]
## Context:
i have member who is unsubscribed to a list and i want to put him back to subscribed status.
I am using `mailchimp.put` method from `mailchimp-api-v3`.

## When i try to set the status to subscribed.
i get a 500.

```{ Error: A deep, internal error has occurred during the processing of your request. Please contact support.
    at Request._callback (~/PROJECT/node_modules/mailchimp-api-v3/index.js:506:30)
    at Request.self.callback (/PROJECT/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/PROJECT/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/PROJECT/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  type: 'about:blank',
  title: 'Internal Server Error',
  status: 500,
  detail: 'A deep, internal error has occurred during the processing of your request. Please contact support.',
  exception: '7eb9e7fff8921402f2de993d54f08b7c',
  instance: 'e882d57b-29ab-4ae0-bc32-b3919fda01b7' }```

**Comment by thorning** [comment]
This looks like an internal error on mailchimps site. If you have a paid mailchimp account, you can properly create a ticket with them. Unfortunately their support seems out of reach for non-paying users.

I would also guess there is a good chance they will catch and correct this error on their own, but unfortunately I don't believe there is anything I can do on my end.

**Comment by thorning** [comment]
I sent a link to this issue to mailchimp, and it seems the likely course is you are trying to resubscribe someone who manually unsubscribed, which is not allowed [Resubscribe a Contact](https://kb.mailchimp.com/lists/manage-contacts/resubscribe-a-contact?utm_source=mc-kb&utm_medium=kb-site&utm_campaign=eepurl).

This should still not send a 500 status back, but seems like a good explanation.
